apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: app-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: app-cronjob
            image: otvoiski/app-cronjob
          restartPolicy: OnFailure